version: "3.9"

services:
  backend:
    volumes:
      - ../:/workspace
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    environment:
      - CHOKIDAR_USEPOLLING=true
